Backtracking
reef-defi/reef-explorer pull request #177
Opened 2022-02-09 20:55 UTC by Frenkiee

2022-02-09 21:32 UTC, frisitano commented on docker-compose.yml
> +    image: reef-explorer-backtracking-dev
We want to reuse the image from the crawler for this service.  Therefore, we should change `reef-explorer-backtracking-dev` to `reef-explorer-crawler-dev`

2022-02-09 21:33 UTC, frisitano commented on docker-compose.yml
> +    build:
we are reusing image from crawler (`reef-explorer-crawler-dev`) so no need to build here, should be fine to remove `build`.

2022-02-10 08:36 UTC, matjazonline requested changes

2022-02-10 08:36 UTC, matjazonline commented on crawler/src/queries/evmEvent.ts
> +      eventData.type = 'Verified';
evmData not eventData

2022-02-10 08:36 UTC, matjazonline commented on crawler/src/queries/evmEvent.ts
> +      raw: { address, topics, data }, parsed: {}, status: 'Success', type: 'Unverified',
- we have `method` saved and status can be seen there 
- type can be seen from data_parsed===null

2022-02-10 08:40 UTC, Frenkiee commented on crawler/src/queries/evmEvent.ts
> +      raw: { address, topics, data }, parsed: {}, status: 'Success', type: 'Unverified',
for status ye we can remove it, but type should stay

2022-02-10 11:44 UTC, frisitano approved these changes

2022-02-10 11:44 UTC, merged