Landing Page Restyle
reef-defi/reef-explorer pull request #31
Opened 2021-10-14 20:12 UTC by samoslag

Restyled landing page with responsive support for smaller screens.

2021-10-15 07:54 UTC, mariopino commented on frontend/components/LastTransfers.vue
> +        <Cell label="Block" :link="`/transfer/${item.hash}`">{{
Label should be `Hash` or `Id`

2021-10-15 10:57 UTC, samoslag commented on frontend/components/LastTransfers.vue
> +        <Cell label="Block" :link="`/transfer/${item.hash}`">{{
Fixed

2021-10-18 13:32 UTC, mariopino requested changes

2021-10-18 13:32 UTC, mariopino commented on frontend/components/LastEvents.vue
> +        :to="`/blocks`"
```suggestion
        :to="`/events`"
```

2021-10-18 13:32 UTC, mariopino commented on frontend/components/LastExtrinsics.vue
> +        :to="`/blocks`"
```suggestion
        :to="`/extrinsics`"
```

2021-10-18 13:32 UTC, mariopino commented on frontend/components/LastTransfers.vue
> +        :to="`/blocks`"
```suggestion
        :to="`/transfers`"
```

2021-10-18 14:05 UTC, mariopino approved these changes

2021-10-18 14:05 UTC, merged