API rewritten
reef-defi/reef-explorer pull request #42
Opened 2021-10-25 20:34 UTC by Frenkiee

- [ ] Backend: handle storing of single / multiple files in db
- [ ] Frontend: manual verification integration
- [ ] Frontend: handle multiple files in contract page

2021-10-29 15:39 UTC, mariopino requested changes

2021-10-29 15:39 UTC, mariopino commented on api/src/queries.ts
> +const UPDATE_CONTRACT_STATUS = `UPDATE contract SET verified = TRUE, processed_bytecode = $1 WHERE contract_id = $2`;
You need to also update in contract table:

- source: how we are going to handle multifile sources?
- compiler_version
- optimization
- runs
- target
- abi (from compilation!)
- license

NOTE: dont need to perform ERC20 token detection, that's handled by crawler.

2021-10-29 15:39 UTC, mariopino commented on api/src/index.ts
> +  console.log(`Timezones by location application is running on port ${config.httpPort}.`);
```suggestion
  console.log(`Reef explorer API is running on port ${config.httpPort}.`);
```

2021-10-29 15:39 UTC, mariopino commented on backend/docker/sql/backend.sql
> +  processed_bytecode TEXT DEFAULT NULL,
Consider adding a new colum `multifile_source` to handle contracts with multiple files.

2021-10-29 15:42 UTC, Frenkiee commented on backend/docker/sql/backend.sql
> +  processed_bytecode TEXT DEFAULT NULL,
no!

2021-10-29 20:11 UTC, mariopino commented
`$ tsc && node ./dist/index.js
src/erc20Checker.ts(1,40): error TS2307: Cannot find module '@ethersproject/abi' or its corresponding type declarations.
src/queries.ts(6,35): error TS2307: Cannot find module 'ethers' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

2021-11-01 09:21 UTC, mariopino commented
Hi @Frenkiee: some contract columns are not being saved in db:

- source
- compiler_version
- optimization
- target

2021-11-02 12:19 UTC, Frenkiee commented
Backend: handle storing of single / multiple files in db -> we are saving all the contracts in the same attribute, which is source! The logic for handling multiple sources is for the frontend to implement and you have it in chat from the last week.
Frontend: manual verification integration -> This is not for this branch to solve. Mario promised to implement it by the end of Friday last week.
Frontend: handle multiple files in contract page -> same as above.

`api/src/api.ts` we do not need it

2021-11-11 16:47 UTC, Netherdrake commented
This PR is already huge, so merging into develop regardless of feature completeness to avoid work on stale branches.

Next PRs should be smaller, faster and more focused.

2021-11-11 16:47 UTC, merged